# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9623f996854279bc9e6620066c4906cfdfd6e54a47adf5144e52e62fea6481a02e2f40d722ee7c928878f94ae263e27e4ca53842ccd9bcb783f623fd04a838a6

test:
  secret_key_base: e44c59f6d767331a18aaa8079cef113d9b98e2c120f8ed56119625858877cfea0f63ba763b7977c4e194dbb51c142b03796820d3a288f5dd122346dfb8fe9b2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
